=== Carlos-Algarrada/MiPrimerRepositorio/xml_programación/Ejercicios xsd/ex1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="relacion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="parentesco" minOccurs="0" >
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string" >
                                            <xs:attribute name="tipo" type="tipoparentesco"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="sexo" type="xs:string"/>
                        <xs:attribute name="carnet" type ="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="tipoparentesco">
        <xs:restriction base="xs:string">
            <xs:enumeration value="padre"/>
            <xs:enumeration value="hija"/>
            <xs:enumeration value="hijo"/>
            <xs:enumeration value="madre"/>
            <xs:enumeration value="otro"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Carlos-Algarrada/MiPrimerRepositorio/xml_programación/Ejercicios xsd/ex1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-->
EJERCICIO1 (ej1.xml,ej1.xsd): Crea un XSD externo asociado al siguiente documento XML de forma que sea válido.
Deberás tener en cuenta las siguientes restricciones:
Los posibles parentescos son (Hijo,Hija,Padre,Madre,Otro)
Y estas restricciones son opcionales pero supondrán un punto extra en la nota del ejercicio.

El email no puede tener una longitud mayor a 250 caracteres.
Los carnets están compuesto de una letra en mayúscula y 4 dígitos.
<?xml version="1.0" encoding="UTF-8"?>
<relacion>
   <persona sexo="hombre" carnet="A1111">
     <nombre>Luis Martin</nombre>
     <email>luis@hotmail.com</email>
     <parentesco tipo="Padre"/>
   </persona>
   <persona sexo="mujer" carnet="B2222">
     <nombre>Laura Martin</nombre>
     <email>laura@hotmail.com</email>
     <parentesco tipo="Hija"/>
   </persona>
   <persona carnet="C3333">
     <nombre>Raul Gonzalez</nombre>
     <email>raul@hotmail.com</email>
     <email>raulin@gmail.com</email>
   </persona>
</relacion>
-->
<relacion
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ex1.xsd"
>
  <persona sexo="hombre" carnet="A1111">
    <nombre>Luis Martín</nombre>
    <email>luis@hotmail.com</email>
    <parentesco tipo="padre"/>
  </persona>
  <persona sexo="mujer" carnet="B2222">
    <nombre>Laura Martín</nombre>
    <email>laura@hotmail.com</email>
    <parentesco tipo="hija"/>
  </persona>
  <persona sexo="hombre" carnet="c3333">
    <nombre>Raul Gonzalez</nombre>
    <email>raul@hotmail.com</email>
    <email>raulin@hotmail.com</email>
  </persona>
</relacion>
